on: [push, pull_request]
name: build
jobs:
  runhaskell:
    name: Haskell Cabal Build + Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.2.1"
          cabal-version: "3.6.2.0"
      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
      - name: Build
        run: cabal build
